### ISSUE TITLE
virus host

### ISSUE THREAD

**Issue by PhiBabs935** [infectious-disease-ontology-extensions/ido-virus#9]
This term is currently a subclass of 'infectious structure host' and 'pathogen host'. But this implies that any host of a virus is a host of a pathogen. Do we really want to say that? What about non-infectious viral particles?

**Comment by johnbeve** [comment]
That implication was intended. What non-infectious virion do you have in mind?

**Comment by PhiBabs935** [comment]
I didn't have anything particular in mind. I just remember us discussing in the summer that not all viruses are infectious, and read about it today after searching on the internet.

I guess it's not a problem if all the cases involving non-infectious virions necessarily involves an infection by an infectious virus as well.

**Comment by johnbeve** [comment]
I think we might be safe given that 'pathogen' and 'infectious' are indexed to specific targets.
